Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/trusty64"
 config.vm.box_version = "20191107.0.0"
 config.vm.network "forwarded_port", guest: 80, host: 8080
 config.vm.provider "virtualbox" do |vb|
  vb.memory = "1024"
  vb.cpus = "1"
 end
 config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get install -y apache2
 SHELL
end
