MACHINES = {
  kernel_update: {
    box_name: "ubuntu/jammy64",
    box_version: "20240912.0.0",
    cpus: 2,
    memory: 1024,
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.provider "virtualbox" do |vb|
        vb.memory = boxconfig[:memory]
        vb.cpus = boxconfig[:cpus]
      end

      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "kernel_update.ansible.yml"
      end
    end
  end
end
