# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  nginx: {
    box_name: "generic/ubuntu2204",
    vm_name: "nginx",
    net: [
      ["192.168.56.11"],
    ],
    ports: [
      [nil, 8080, 8080]
    ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[0]
      end

      boxconfig[:ports].each do |port|
        box.vm.network "forwarded_port", id: port[0], guest: port[1], host: port[2], auto_correct: true
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end
  end
end